image: rocker/verse:4.5.0

pages:
  stage: deploy
  before_script:
    # install R packages
    - install2.r ggplot2 dplyr kableExtra
    # # Install renv and restore project dependencies
    # - R -e "install.packages('renv')"
    # - R -e "renv::restore(confirm = FALSE)"

    # Install pip and Python packages
    - apt-get update && apt-get install -y python3-pip
    - pip3 install --no-cache-dir --break-system-packages pandas matplotlib numpy jupyter itables seaborn
    - apt-get clean && rm -rf /var/lib/apt/lists/*

  script: 
  - cd contents
  - quarto render
  - mkdir ../public/
  - cp -r ./_site/* ../public/

 
  artifacts:    
    paths:
    - public    
    
  only:
  - main
  interruptible: true
