project:
  type: website
            
website:
    title: Home
    page-navigation: true
    back-to-top-navigation: true
    page-footer:        
        left: |
          Made with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) \
          \ by the [Center for Reproducible Science](https://www.crs.uzh.ch/en.html)
        
       
        right: |
           Free under the [CC BY international license 4.0 ](https://creativecommons.org/licenses/by/4.0/). \
           \ Source code on [![](https://images.ctfassets.net/xz1dnu24egyd/1hnQd13UBU7n5V0RsJcbP3/769692e40a6d528e334b84f079c1f577/gitlab-logo-100.png){fig-alt="Git" width=65px}](https://gitlab.uzh.ch/crsuzh/Workshop_Quarto_2024_UNIGE) 
           
           
    favicon:  'assets/Logo_CRS_col.svg'
    
    site-url: https://crsuzh.pages.uzh.ch/Workshop_Quarto_2024_UNIGE/
    repo-url: https://gitlab.uzh.ch/crsuzh/Workshop_Quarto_2024_UNIGE       
    
    navbar:        
        #logo: assets/Logo_CRS_col.svg        
        collapse-below: lg
        
        right:                  
          - text: "Instructions"            
            href: ./instructions/index.qmd
          # Temporarily hidden sections
          # - text: "Intro"            
          #   href: ./slides_intro/index.qmd
          # - text: "Demo"            
          #   href: ./demo/index.qmd
          # - text: "Outro"            
          #   href: ./slides_outro/index.qmd                 
                 
format:
    html:         
        grid:
          sidebar-width: 350px
        theme:
          light: litera
          dark: darkly
        highlight-style: a11y
        code-link: true
        toc: true
        toc-expand: 4
        code-copy: true              
        mermaid: 
          theme: default

freeze: auto

