---
title: "Installation Instructions" 
author:
  - name: "Gorka Fraga González"
    orcid: 0000-0002-1857-8607
    
  - name: "Fabio Molo"
    orcid: 0000-0001-9320-5854

  - name: "Samuel Pawel"
    orcid: 0000-0003-2779-320X
date: "November 14, 2025"

---

## Requirements 

### R and RStudio

To follow along in the hands-on part of the workshop, you need to have R and RStudio (v2022.07 or later) installed, which can be downloaded here: <https://www.r-project.org/> and here: <https://posit.co/download/rstudio-desktop/>. ```Quarto``` is then included in the RStudio installation. 

### R Packages

We will use the following additional R packages in the workshop. You can install them on the spot or beforehand by typing the following code in the **R console**: 
```r
install.packages(c("quarto", "dplyr", "ggplot2"))
``` 

### LateX for rendering PDFs (optional)

To render documents in PDF format, ```Quarto``` needs to be able to access ```LaTeX```. If you do not already have ```LaTeX``` installed, you can install the light-weight version ```TinyTex``` by typing the following in your **Terminal**:

```bash
quarto install tinytex
```

Additional instructions regarding ```LaTeX```, can be found here: <https://quarto.org/docs/output-formats/pdf-basics.html>


## Alternative 1: Python (optional)

In the workshop we will use R and RStudio for demonstration, but ```Quarto``` can also be used with Python instead of R and with VS Code, Jupyter Notebooks or other development environments instead of RStudio.

To get up and running with Python, first install Quarto and pick your favorite development environment by following the [instructions here](https://quarto.org/docs/get-started/) (we will use VS Code in the hands-on demo). If you don't yet have Python 3 on your system, we recommend you install a version using the standard installer from <https://www.python.org/downloads/>. We will use a few additional Python packages in the workshop. It is best practice to always install Python packages in virtual environments, for example, using [venv](https://docs.python.org/3/library/venv.html) (included in Python) or [conda](https://docs.conda.io/projects/conda/en/stable/user-guide/install/index.html) (separate installation).

::: {.panel-tabset}

#### venv

```bash
python -m venv quarto-env
source quarto-env/bin/activate
pip install --upgrade pip
pip install pandas matplotlib numpy jupyter itables seaborn
```

#### conda

```bash
conda create -n quarto-env python=3.12
conda activate quarto-env
conda install pandas matplotlib numpy jupyter seaborn
```

::: {.callout-caution}
##### Kernels from Conda

If you are using a kernel that is contained within an external conda environment you need to take an extra step to make sure it is recognized by Quarto. Please follow the instructions here to make conda managed kernels available:

<https://github.com/Anaconda-Platform/nb_conda_kernels#use-with-nbconvert-voila-papermill>

Note that this step is not required if you are merely using conda with Quarto. It applies to using kernels other than the default Python kernel that happen to be installed within a conda environment separate from the one you are using.
:::

:::

::: {.callout-note}
Note: The above package install commands don't specify the package versions. To exactly reproduce the results from the hands-on demo, download `requirements.txt` from this site's [GitLab repository](https://gitlab.uzh.ch/crsuzh/workshop-quarto-2025-unige) and install the packages using `pip install -r requirements.txt` instead.
:::

## Alternative 2: Working from the Posit cloud (optional)

If you do not want to install anything on your computer you can also use a cloud version of R and RStudio. Sign up at the **Posit Cloud** (<https://login.posit.cloud>) and:

-  register with your email address and choose a password;
-  select the "Free Cloud" subscription option.
-  Once logged in, go to your workspace and click on `New Project` (top right corner), then choose `New RStudio Project`.  

## Alternative 3: Docker (optional)

This option is for advanced users who have [Docker](https://www.docker.com/) installed on their system. Change to a new directory for the workshop and copy the Dockerfile from this website's [GitLab repository](https://gitlab.uzh.ch/crsuzh/workshop-quarto-2025-unige). Then, build the Docker image:

```bash
docker build -t pyverse .
```

Run a live dev session:

```bash
docker run -d -p 8787:8787 -e PASSWORD=rstudio \
  -v "$(pwd)":/home/rstudio/project pyverse
```

Open RStudio Server at <http://localhost:8787/> and create a new `.qmd``Quarto file.